Ft implement designs signup/registration 160088425
andela/ah-titans-frontend pull request #12
Opened 2018-08-30 13:10 UTC by petermwash

#### What does this PR do?
Design an implementation for signup container.

#### Description of tasks to be completed
Implement designs for the Signup/Registration Page.

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans-frontend.git
```
```sh
$ git checkout ft-implement-designs-signup/registration-160088425
```
```sh
$ cd ah-titans-frontend
```

>Install the dependencies using the command below.

```sh
$ npm install
```
>Run the application as below.
```sh
$ npm start
```
>Now you can navigate to the link 'https://http://localhost:8080/signup' on your browser and you should be able to see a page as the one shown on the screenshot below.

<img width="1280" alt="screen shot 2018-08-30 at 15 13 38" src="https://user-images.githubusercontent.com/27728464/44853591-06c94080-ac6f-11e8-98be-e380fbcf08c9.png">

#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#160088425](https://www.pivotaltracker.com/story/show/160088425)

2018-08-30 13:11 UTC, dcDalin commented
<!--
  0 failure: 
  1 warning:  Missing Test File...
  
  
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Missing Test Files:
  - `src/Header/__tests__/index.js`
- `src/Home/__tests__/index.js`
- `src/Login/__tests__/index.js`
- `src/views/App/__tests__/index.js`
- `src/views/Main/__tests__/index.js`
- `tests/Router/__tests__/router.test.js`
- `tests/components/__tests__/homepage.test.js`
- `tests/components/__tests__/login.test.js`
  If these files are supposed to not exist, please update your PR body to include "Skip New Tests".
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-08-30 15:06 UTC, jmnyarega requested changes
Covert .css to .scss & .js  to .jsx in your files

2018-08-30 15:50 UTC, jmnyarega approved these changes

2018-08-30 15:54 UTC, migot01 approved these changes

2018-08-30 18:48 UTC, merged

2018-09-06 09:56 UTC, evansmusomi commented on src/Signup/components/Signup.scss
> +from {
Is there a html element named "from" or was this meant to be ".from" or "form" @petermwash?

2018-09-06 10:40 UTC, migot01 commented on src/Signup/components/Signup.scss
> +from {
@evansmusomi this had been remedied and a new signup UI created in PR 14 to match the mockup previously done
 https://github.com/andela/ah-titans-frontend/pull/14

2018-09-07 06:17 UTC, petermwash commented on src/Signup/components/Signup.scss
> +from {
@evansmusomi I noted that and I had corrected it but on the current UI we completely got rid of it since we are now using react-materialize.