#160244936 Implement designs for creating an article
andela/ah-titans-frontend pull request #17
Opened 2018-09-04 10:26 UTC by petermwash

#### What does this PR do?
Implement designs for creating an article.

#### Description of tasks to be completed
Implement designs for creating a new article and it should match the mockup design.

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans-frontend.git
```
```sh
$ git checkout -b ft-implement-designs-for-creating-an-article-160244936
```
```sh
$ cd ah-titans-frontend
```

> Install the dependencies with the command below.

```sh
$ npm install
```
>Then run the app with the command below.
```sh
$ npm start
```
Now navigate to the URL "http://localhost:8080/article" and should see a page as the one shown on the screenshot below.

<img width="1280" alt="screen shot 2018-09-04 at 13 24 45" src="https://user-images.githubusercontent.com/27728464/45026104-f685dc80-b045-11e8-99ba-ffccb968c562.png">

#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#160244936](https://www.pivotaltracker.com/story/show/160244936)

2018-09-04 10:27 UTC, dcDalin commented
<!--
  1 failure:  a `console.log` w...
  1 warning:  :exclamation: Big PR
  
  
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  a `console.log` was left in file (dangerfile.js)
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :exclamation: Big PR
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-09-04 10:44 UTC, johnmusiu approved these changes

2018-09-04 10:47 UTC, ronaldndirangu requested changes
Great work guys. However, I would recommend using a reach text editor like draft.js to improve the user experience.

2018-09-04 11:38 UTC, petermwash commented
@ronaldndirangu I think if we use draft.js it will change the whole view of the page and it will differ from the mockup we had earlier. I would recommend we consult with the PO on that and probably create a story for this.

2018-09-04 11:49 UTC, ronaldndirangu approved these changes

2018-09-04 11:50 UTC, ronaldndirangu commented
@petermwash that makes sense. We can make the changes later if the team requires it.

2018-09-04 13:38 UTC, migot01 approved these changes

2018-09-04 17:12 UTC, jmnyarega commented
Please update your branch @petermwash

2018-09-05 07:50 UTC, janetnim commented
Also, you should also consider adding image upload option on the template

2018-09-05 09:08 UTC, jmnyarega commented on src/Header/components/index.js
> +
Lose this line

2018-09-05 12:04 UTC, petermwash commented
@jmnyarega Fixed.

2018-09-05 14:13 UTC, merged