#160011177 Login functionality
andela/ah-titans-frontend pull request #19
Opened 2018-09-05 14:35 UTC by chepmanu

#### What does this PR do?
Lets a user login to the application using their email

#### Description of tasks to be completed
Enable user login functionality.
#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans-frontend.git
```
```sh
$ cd ah-titans-frontend
```
```sh
$ git checkout ft-login-functionality-160011177
```
>Install the dependencies using the command below.

```sh
$ npm install
```
>Run the application as below.
```sh
$ npm start
```

#### Any background context you want to provide?
>A user has to be signed up in order to log in.

#### Screenshots of the page and how errors are displayed.
![image](https://user-images.githubusercontent.com/28649357/45100294-dcc1c380-b131-11e8-94a5-607c21031141.png)
![image](https://user-images.githubusercontent.com/28649357/45100353-f82cce80-b131-11e8-859a-e10641205669.png)

#### What are the relevant Pivotal Tracker Stories?
[#160011177](https://www.pivotaltracker.com/story/show/160011177)

2018-09-05 14:38 UTC, dcDalin commented
<!--
  0 failure: 
  2 warning:  :exclamation: Big PR, Missing Test File...
  
  
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :exclamation: Big PR
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  Missing Test Files:
  - `./__tests__/.eslintrc.js`
- `src/Login/components/__tests__/index.js`
- `src/Main/components/__tests__/index.js`
- `src/Main/__tests__/main.test.js`
- `src/reducers/__tests__/index.js`
- `src/__tests__/setupEnzyme.js`
  If these files are supposed to not exist, please update your PR body to include "Skip New Tests".
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-09-06 08:08 UTC, evansmusomi commented on src/Login/components/LoginForm.js
> +    // const error = this.props.signup.error;
@chepmanu, it looks like this was left here by mistake. Please delete it if it's no longer relevant.

2018-09-06 08:21 UTC, evansmusomi commented on src/actions/loginActions.js
> +  .then(res => handleResponse(res));
Fetch requests that don't resolve as expected don't appear to be handled. I recommend having a catch clause for that if this case hasn't been handled. @chepmanu

2018-09-06 08:27 UTC, evansmusomi commented
@chepmanu The UI looks as indicated in the screenshots 👍 

I appreciate that users need to be signed up to log in successfully as mentioned in the PR.  When I tried logging in I expected to see a relevant validation message but instead saw a blank white screen. **Please look into this**.

In future, you can also consider including test account details that could be used to verify the success path of your story in the PR description or PT story.

2018-09-06 08:34 UTC, jmnyarega requested changes

2018-09-06 08:34 UTC, jmnyarega commented on src/Login/components/LoginForm.js
> +      <div className="card">
Since we are making use of `react-materialize`, please make use of already created components.

2018-09-06 08:34 UTC, jmnyarega commented on src/Login/components/LoginForm.js
> +                onChange={onChange}
same here, make use of `react-materialize` components

2018-09-06 08:34 UTC, jmnyarega commented on src/Login/components/LoginForm.js
> +  @@ -40,4 +68,9 @@ const SignupForm = () => (
Why do we have this ` @@ -40,4 +68,9 @@` here?

2018-09-06 08:34 UTC, jmnyarega commented on src/Login/components/index.js
> +          <div className="error">{errors.email}</div>
Look into `react-materialize` to see if there is a component which can gracefully handle notifications

2018-09-06 08:34 UTC, jmnyarega commented on src/Login/components/index.js
> +            <Button waves="light" onClick={onClick} disabled={isFetching} style={{ width: '80%', }}>
It will be nice if we formatted this  👇 
```
<Button 
   waves="light" 
   onClick={onClick} 
   disabled={isFetching} 
   style={{ width: '80%', }}
>

```

2018-09-06 08:34 UTC, jmnyarega commented on src/Login/components/index.scss
> +}
Add an extra line at the end of the file

2018-09-06 08:34 UTC, jmnyarega commented on src/Login/containers/Login.js
> +  }
Please make this an `arrow function` to avoid binding it in the constructor 👇 

```
  handleChange = (e) => {
     this.setState({ [e.target.name]: e.target.value, });
  }

```

2018-09-06 08:34 UTC, jmnyarega commented on src/Login/containers/Login.js
> +  }
Make it an arrow function too

2018-09-06 08:34 UTC, jmnyarega commented on src/actions/loginActions.js
> +})
To avoid repeating this headers, we can have them declared somewhere and re-used

2018-09-06 08:34 UTC, jmnyarega commented on src/actions/tests/login.test.js
> +
Lose this extra line

2018-09-06 08:51 UTC, ronaldndirangu commented on src/Login/components/LoginForm.js
> +      <div className="card">
This LoginForm.js is an old file that we will get rid off it seems it was pushed by mistake. We will update the branch.

2018-09-06 08:57 UTC, ronaldndirangu commented on src/Login/containers/Login.js
> +  }
We are currently looking into this as a team. The babel configuration for this is not working as expected but we are looking into it.

2018-09-06 08:58 UTC, ronaldndirangu commented on src/actions/loginActions.js
> +})
We are planning to have a story to move all the fetch functions to another file for uniformity in our imports for different actions.

2018-09-06 09:00 UTC, chepmanu commented on src/actions/loginActions.js
> +  .then(res => handleResponse(res));
@evansmusomi The catch clause is included in the loginUser function when dispatching the loginUserError.

2018-09-06 09:00 UTC, ronaldndirangu commented on src/Login/components/index.js
> +          <div className="error">{errors.email}</div>
For uniformity between the login and signup pages error messages display we had used this div to indicate the error above the specific field having the error to act as a pointer for the end user.

2018-09-06 09:00 UTC, ronaldndirangu commented on src/Login/components/index.js
> +          <div className="error">{errors.email}</div>
But we can discuss with the team how we can better display this errors.

2018-09-06 09:02 UTC, chepmanu commented on src/Login/components/LoginForm.js
> +                onChange={onChange}
That form has been done away with. The new one will be pushed soon.

2018-09-06 09:19 UTC, evansmusomi commented on src/actions/loginActions.js
> +      dispatch(dispatch(loginUserSuccessful(data)));
@chepmanu, is the use of nested dispatch calls intentional here? If yes, why is it necessary?

2018-09-06 09:24 UTC, jmnyarega commented on src/Login/containers/Login.js
> +  }
Kindly make sure this is fixed.

2018-09-06 09:27 UTC, jmnyarega commented on public/index.html
>    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
Are by any chance using `Jquery` ? 😮

2018-09-06 09:30 UTC, ronaldndirangu commented on src/actions/loginActions.js
> +      dispatch(dispatch(loginUserSuccessful(data)));
It is not necessary we have rectified this.

2018-09-06 09:35 UTC, ronaldndirangu commented on src/Login/containers/Login.js
> +  }
We tried configuring this on the signup and login containers since yesterday with no success we might need your help on this.

2018-09-06 10:24 UTC, chepmanu commented on public/index.html
>    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
The react-materialize library show that it is required I think it is used to provide features such as snackbars.

2018-09-06 14:30 UTC, jmnyarega commented on src/actions/loginActions.js
> +})
Kindly add a story for it on PT

2018-09-06 14:31 UTC, ronaldndirangu commented on src/actions/loginActions.js
> +})
Okay

2018-09-06 15:52 UTC, johnmusiu approved these changes

2018-09-06 16:13 UTC, migot01 approved these changes

2018-09-06 16:25 UTC, janetnim approved these changes

2018-09-07 04:26 UTC, jmnyarega approved these changes

2018-09-07 04:28 UTC, merged