#160319094 Add utility file and add environmental variables
andela/ah-titans-frontend pull request #23
Opened 2018-09-11 07:41 UTC by chepmanu

#### What does this PR do?
Adds files for fetch method, config and environmental variables.

#### Description of tasks to be completed
Have our environmental variables in our .env file and have one method to handle all fetch methods.

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans-frontend.git
```
```sh
$ git checkout ch-fetch-method-file-160319094
```
```sh
$ npm install
```
```sh
$ npm start
```
#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#160319094](https://www.pivotaltracker.com/story/show/160319094)

2018-09-11 07:43 UTC, dcDalin commented
<!--
  0 failure: 
  1 warning:  :exclamation: Big PR
  
  
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :exclamation: Big PR
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-09-11 07:46 UTC, janetnim approved these changes

2018-09-11 07:48 UTC, ronaldndirangu requested changes

2018-09-11 07:48 UTC, ronaldndirangu commented on src/utils/auth_header.js
> +    return { Authorization: `Bearer ${user.token}`, };
We didn't used the Bearer keyword to identify our tokens we used the Token keyword. Please change that here

2018-09-11 07:48 UTC, ronaldndirangu commented on src/utils/service.js
> +const handleResponse = response => response.text().then((text) => {
There is no need to convert the response to text as we already know the response is a JSON object. Just user the response.json() to clean up the code.

2018-09-11 07:50 UTC, ronaldndirangu commented
I think you should also test these fetch functions by mocking the requests and responses to improve our test coverage.

2018-09-11 07:56 UTC, janetnim requested changes
Maybe change ```Bearer``` header to ```Token```

2018-09-11 12:49 UTC, janetnim approved these changes

2018-09-11 12:49 UTC, ronaldndirangu approved these changes

2018-09-12 03:23 UTC, johnmusiu reviewed
Just wondering why we should have `.env` and `example.env`. I thought `.env` should be ignored in `.gitignore` file.

2018-09-12 03:29 UTC, johnmusiu approved these changes

2018-09-12 07:33 UTC, jmnyarega requested changes

2018-09-12 07:33 UTC, jmnyarega commented on src/utils/auth_header.js
> +const authHeader = (authenticated) => {
Please, can we have this function documented?

2018-09-12 07:47 UTC, chepmanu commented on src/utils/auth_header.js
> +const authHeader = (authenticated) => {
Ok, am getting that done in a minute.

2018-09-12 07:57 UTC, jmnyarega approved these changes

2018-09-12 07:57 UTC, merged