#160011176 Reset password with email link
andela/ah-titans-frontend pull request #28
Opened 2018-09-14 06:34 UTC by dcDalin

#### What does this PR do?
Allows users to reset their password 

#### Description of tasks to be completed
Users can receive an email to reset their password

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans.git
```
```sh
$ git checkout -b ft-reset-password-160011176
```
```sh
$ npm install
```

#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#160011176]https://www.pivotaltracker.com/story/show/160011176)

#### Screenshots

<img width="1133" alt="forgot1" src="https://user-images.githubusercontent.com/30606041/45533709-4ceeda00-b801-11e8-8d5f-d03988c7161f.png">

<img width="905" alt="forgot2" src="https://user-images.githubusercontent.com/30606041/45533722-537d5180-b801-11e8-8cae-08c68911d051.png">

<img width="733" alt="forgot3" src="https://user-images.githubusercontent.com/30606041/45533732-5aa45f80-b801-11e8-80d5-5e38becb6e87.png">

<img width="1059" alt="forgot4" src="https://user-images.githubusercontent.com/30606041/45533746-642dc780-b801-11e8-9249-c2468e36aec5.png">

2018-09-14 06:36 UTC, dcDalin commented
<!--
  0 failure: 
  1 warning:  :exclamation: Big PR
  
  
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :exclamation: Big PR
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-09-16 17:09 UTC, jmnyarega requested changes

2018-09-16 17:09 UTC, jmnyarega commented on .babelrc
> +    "transform-object-rest-spread"
Why do we have these libraries added?

2018-09-16 17:09 UTC, jmnyarega commented on public/index.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
Since we are using materialize, can't we use materialize icons?

2018-09-16 17:09 UTC, jmnyarega commented on public/index.html
> +</html>
An extra line required

2018-09-16 17:09 UTC, jmnyarega commented on src/Main/components/index.js
>  const token = localStorage.getItem('token');
Just saying: It is a bad idea storing user data in local storage, FYI I have created a story to store user information in the redux store

2018-09-16 17:09 UTC, jmnyarega commented on src/Password/NewPass/components/index.test.js
> +});
Can we have more tests here
 1. Check if password provide is in expected length
 2. Check for fields, whether they are empty.

Please cover above and more edge cases

2018-09-16 17:09 UTC, jmnyarega commented on src/Password/NewPass/components/index.js
> +					</Row>
I am seeing any client-side validation, can we have implemented ?

2018-09-16 17:09 UTC, jmnyarega commented on src/Password/NewPass/containers/index.js
> +
An extra line needed

2018-09-16 17:09 UTC, jmnyarega commented on src/Password/NewPass/containers/index.js
> +    if (data.new_password.length < 8) errors.new_password = "Password should be at least 8 characters";
What we are doing here is displaying errors that come from the backend 💃 Which is good. Question. Do I have to wait for the errors from the backend to be notified that password does not match or fields are empty? Please let us have client-side validation to avoid overloading the server

2018-09-16 17:09 UTC, jmnyarega commented on src/Password/NewPass/containers/index.test.js
> +import { shallow, mount, render } from 'enzyme';
`mount` and `render` are not being used here

2018-09-16 17:09 UTC, jmnyarega commented on src/Password/NewPass/index.js
> +    call({
This function is supposed to be called in the thunk.

2018-09-16 17:09 UTC, jmnyarega commented on src/Password/NewPass/index.js
> +
An extra line here

2018-09-16 17:09 UTC, jmnyarega commented on src/Password/NewPass/index.js
> +	submit = data => this.props.newpass(data).then((res) => swal("Success", `${res.reset} Click OK to login`, "success" ).then(() => this.props.history.push('/login')));
Can we have this function well formatted? There is no need for making it inline. 
Also make use of the redux pattern to get responses from the server

2018-09-16 17:09 UTC, jmnyarega commented on src/Password/ResetPass/containers/index.js
> +  onChange = e => this.setState({ data: { ...this.state.data, [e.target.name]: e.target.value}});
Again, lets gets this function well formatted, no need to make this an inline function -> This makes the code unreadable

2018-09-16 17:09 UTC, jmnyarega commented on src/Password/ResetPass/containers/index.js
> +			this.props
I think the indentation is so off here

2018-09-16 17:09 UTC, jmnyarega commented on src/Password/ResetPass/index.js
> +  submit = data => this.props.reset(data).then(() => swal("Success", "Check your email inbox for password reset instructions!", "success" ).then(() => this.props.history.push('/login')));
Check the earlier review about inline function

2018-09-16 17:09 UTC, jmnyarega commented on src/Password/ResetPass/index.js
> +export default connect(null, {reset})(ResetPass);
An extra line needed

2018-09-16 17:09 UTC, jmnyarega commented on src/actions/api.js
> +export default {
What does api.js do? from reading the filename I am not getting it's real function

2018-09-16 17:09 UTC, jmnyarega commented on src/actions/tests/newPass.test.js
> +const mockStore = configureMockStore(middlewares);
Since you are only testing action creators here, no need to have these variables declared

2018-09-16 17:09 UTC, jmnyarega commented on src/actions/tests/passReset.test.js
> +const mockStore = configureMockStore(middlewares);
Refer my earlier comment

2018-09-16 17:15 UTC, jmnyarega commented
Please have the following components/containers transferred to a `common` folder
1. src/Password/NewPass/components/index.js
2.src/Password/NewPass/components/index.test.js
3. src/Password/NewPass/containers/index.js
4.  src/Password/NewPass/containers/index.test.js 
5.  src/Password/NewPass/index.js 
6. src/Password/ResetPass/containers/index.js

2018-09-16 17:15 UTC, jmnyarega commented
Kindly resolve the conflicts

2018-09-17 06:38 UTC, dcDalin commented on .babelrc
> +    "transform-object-rest-spread"
@jmnyarega for transformation of class properties. It also allows usage of fat arrow functions.

2018-09-17 06:38 UTC, dcDalin commented on public/index.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
Yes @jmnyarega , The CDN link is for materialize icons.

2018-09-17 06:43 UTC, dcDalin commented on src/Main/components/index.js
>  const token = localStorage.getItem('token');
@jmnyarega, I did not touch any code regarding the local storage.

2018-09-17 06:44 UTC, dcDalin commented on src/Password/NewPass/components/index.test.js
> +});
@jmnyarega thank you, let me work on the edge cases.

2018-09-17 06:52 UTC, dcDalin commented on src/actions/api.js
> +export default {
I love to have all my api calls in one file @jmnyarega. It sort of reduces the complexity.

2018-09-17 07:42 UTC, dcDalin commented on src/Password/NewPass/components/index.js
> +					</Row>
Client-side validation has been implemented. It works based on keyup event.

2018-09-17 07:44 UTC, dcDalin commented on src/Password/NewPass/containers/index.js
> +    if (data.new_password.length < 8) errors.new_password = "Password should be at least 8 characters";
No @jmnyarega, These are client-side validation. They don't at any point touch the server.

2018-09-17 07:59 UTC, dcDalin commented on src/Password/NewPass/index.js
> +    call({
@jmnyarega, don't you think adding it to redux will be an overkill as it only gets the message.

2018-09-20 11:57 UTC, jmnyarega requested changes

2018-09-20 11:57 UTC, jmnyarega commented on .circleci/config.yml
> +            yarn test --u --coverage
Why was this file modified?

2018-09-20 11:57 UTC, jmnyarega commented on public/index.html
> +</html>
Extra line at the end of the file required

2018-09-20 11:57 UTC, jmnyarega commented on src/Common/NewPass/containers/index.js
> +  onChange = e => this.setState({ data: { ...this.state.data, [e.target.name]: e.target.value}});
Again, let's have this function verbosely written, well documented and also give it a more descriptive name 
```jsx
descriptiveName = () => {
  // statements
}

2018-09-20 11:57 UTC, jmnyarega commented on src/Common/NewPass/containers/index.js
> +  onValidate = () => {
Descriptive function name here, sounds generic yet it is used just within the file

2018-09-20 11:57 UTC, jmnyarega commented on src/Common/NewPass/containers/index.js
> +
Remove this extra line here, NOTE: you should only have exactly one line at the end of each file

2018-09-20 11:57 UTC, jmnyarega commented on src/Common/NewPass/index.js
> +
Same here, remove this extra line at the end of this file, only one is needed

2018-09-20 11:57 UTC, jmnyarega commented on src/Common/ResetPass/components/InlineError.js
> +
Lose these line

2018-09-20 11:57 UTC, jmnyarega commented on src/Common/ResetPass/components/index.js
> +
Lose this line too

2018-09-20 11:57 UTC, jmnyarega commented on src/Common/ResetPass/containers/index.js
> +  onChange = e => this.setState({ data: { ...this.state.data, [e.target.name]: e.target.value}});
Refer my earlier comment about creating more readable functions

2018-09-20 11:57 UTC, jmnyarega commented on src/Common/ResetPass/containers/index.js
> +  }
Again functions on lines 19, 28, 33  should have a more descriptive name

2018-09-20 11:57 UTC, jmnyarega commented on src/Main/components/index.js
> +      <Route exact path="/resetpass" component={ResetPass} />
Kindly have this well formatted

2018-09-20 11:57 UTC, jmnyarega commented on src/actions/newPass.js
> +export const checkURL = (uidb64, token, history) => (dispatch) => {
Let's have all functions well documented

2018-09-20 11:57 UTC, jmnyarega commented on src/actions/newPass.js
> +export const newpass = credentials => dispatch => api.pass.newpass(credentials).then(reset => dispatch(userNewPass(reset)));
refer to my earlier comment about writing readable functions

2018-09-20 13:46 UTC, dcDalin commented on .circleci/config.yml
> +            yarn test --u --coverage
@jmnyarega `--u` flag is used to update the snapshot tests.

2018-09-21 05:22 UTC, merged