#160532247 Switch to Axios
andela/ah-titans-frontend pull request #29
Opened 2018-09-15 15:41 UTC by chepmanu

#### What does this PR do?
Implements axios for our API calls.

#### Description of tasks to be completed
Our API calls to be handled using axios.

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans-frontend.git
```
```sh
$ cd ah-titans-frontend
```
```sh
$ git checkout -b ft-switch-to-axios-160532247
```
```sh
$ npm install
```

#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#160532247](https://www.pivotaltracker.com/story/show/160532247)

2018-09-15 15:43 UTC, dcDalin commented
<!--
  1 failure:  a `console.log` w...
  1 warning:  :exclamation: Big PR
  
  
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  a `console.log` was left in file (src/utils/service.js)
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :exclamation: Big PR
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-09-16 16:23 UTC, jmnyarega commented on src/actions/loginActions.js
> +			history.push('/');
Just mentioning, It is bad practice to do re-routing inside thunks, this deviates from the _single responsibility principle_ in computer science. A good practice will be creating a separate component to handle routing. 
Sources which can help:
   1.  https://reacttraining.com/react-router/web/example/auth-workflow
   2. https://reacttraining.com/react-router/web/api/Redirect

2018-09-16 16:26 UTC, jmnyarega commented on src/actions/loginActions.js
> -      localStorage.setItem('username', data.user.username);
Removing this piece of code will break our application, please revert the implementation. FYI I have created a separate story to add user information in the redux store.

2018-09-16 16:27 UTC, jmnyarega commented on src/utils/auth_header.js
> +	// const { user } = JSON.parse(data);
Remove this commented code

2018-09-16 16:42 UTC, jmnyarega requested changes

2018-09-16 16:42 UTC, jmnyarega commented on src/actions/signup.js
> +const createUser = ({ user, history }) => (dispatch) => {
Please document this function

2018-09-16 16:42 UTC, jmnyarega commented on src/utils/headers.js
> +	// const { token2 } = JSON.parse(token);
Again, we don't push commented code

2018-09-16 16:42 UTC, jmnyarega commented on src/utils/service.js
> +}) => axios(`${config.BASE_URL}${endpoint}`, {
I am so confused here 😕

2018-09-16 16:42 UTC, jmnyarega commented on src/actions/loginActions.js
> +			dispatch(loginUserError(error.response.data));
Can we do some destructing here
 ` const { errorResponse } = error.response;`
and then you can have 
`dispatch(loginUserError(errorResponse.data));`

2018-09-16 16:42 UTC, jmnyarega commented on src/actions/signup.js
> +			dispatch(createUserErrorActionCreator(error.response.data));
Again, do some destructing

2018-09-16 16:42 UTC, jmnyarega commented on src/utils/jwtDecode.js
> +	if (token.length === 2) {
The logic here is wrong, You are basically checking whether the length of the token _string_ is **2** then you decode it 🍿. A more reasonable why will be:
- Split the string into an array using the _split_ function. 👉 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split
- Then check the length of the string before decoding the token

2018-09-16 16:42 UTC, jmnyarega commented on src/utils/service.js
> +});
Why are we handling promises in this file? 😕

2018-09-16 16:43 UTC, jmnyarega commented on package.json
>      "lodash": "^4.17.10",
Can we get rid of this library? I have seen it's usage so far.

2018-09-16 17:05 UTC, chepmanu commented on src/utils/service.js
> +}) => axios(`${config.BASE_URL}${endpoint}`, {
I had changed to using Axios for that file, I am waiting for a thumbs up from the team to get rid of that file completely as they get to shift to the new utility file. But for the moment I will return fetch until all are able to shift to the new utility file with Axios.

2018-09-16 17:05 UTC, chepmanu commented on src/utils/headers.js
> +	// const { token2 } = JSON.parse(token);
Will make the changes ASAP.

2018-09-16 17:08 UTC, chepmanu commented on src/actions/signup.js
> +const createUser = ({ user, history }) => (dispatch) => {
Thank you for the suggestion, that was a function that was written by others, I only made a simple modification to it. I will, however, go ahead and document it for the sake of having better code overall.

2018-09-16 17:12 UTC, chepmanu commented on src/utils/service.js
> +});
I will revert to the old file model that had a response handler(the one with fetch instead of Axios). This will be until everyone has shifted to using the new Axios model. Both files will be up and the one with fetch will be done away with later.

2018-09-16 17:14 UTC, chepmanu commented on src/utils/jwtDecode.js
> +	if (token.length === 2) {
I will remove the file completely as it is not currently used.

2018-09-16 17:16 UTC, chepmanu commented on src/actions/loginActions.js
> +			dispatch(loginUserError(error.response.data));
Thank you for the suggestion, changes coming up shortly.

2018-09-16 17:16 UTC, chepmanu commented on src/actions/signup.js
> +			dispatch(createUserErrorActionCreator(error.response.data));
Thank you for the suggestion, changes coming up shortly.

2018-09-16 17:40 UTC, chepmanu commented on package.json
>      "lodash": "^4.17.10",
I will remove it.

2018-09-16 19:00 UTC, jmnyarega commented on src/utils/jwtDecode.js
> +	if (token.length === 2) {
Please don't, we will use this to decode user information from the token and add it to the store.

2018-09-16 19:04 UTC, jmnyarega commented on src/actions/signup.js
> +
Remove these two empty lines between the documentation and the function

2018-09-18 08:16 UTC, jmnyarega requested changes

2018-09-18 08:16 UTC, jmnyarega commented on src/utils/headers.js
> +
Lose this line

2018-09-18 08:16 UTC, jmnyarega commented on src/utils/jwtDecode.js
> +	const token2 = token.split('');
Can we have a better variable name for this ? `token2` 🤔

2018-09-18 08:30 UTC, jmnyarega requested changes

2018-09-18 08:30 UTC, jmnyarega commented on src/actions/loginActions.js
> +			const { ...errorResponse } = error.response;
Change this to 
```jsx
  const { data } = error.response;
  dispatch(createUserErrorActionCreator(data));
```

What you have implemented will not work because, you are telling the compile to spread `errorResponse `(Which is probably and array) and the use the spread values to destructure the
```jsx 
error.response
```

Object

2018-09-18 08:30 UTC, jmnyarega commented on src/actions/signup.js
> +			const { ...errorResponse } = error.response;
Refer to my earlier comment

2018-09-18 17:47 UTC, jmnyarega approved these changes

2018-09-18 17:53 UTC, johnmusiu approved these changes

2018-09-18 18:01 UTC, merged