#160538683 Implements update state from local storage
andela/ah-titans-frontend pull request #31
Opened 2018-09-18 13:00 UTC by johnmusiu

#### What does this PR do?
Implements update state from local storage

#### Description of tasks to be completed
Checks if a token exists on localStorage and updates the state with the user details found in the token.
If there is no token state is not updated.

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans-frontend.git
```
```sh
$ cd ah-titans-frontend
```
```sh
$ git checkout -b ch-store-user-data-in-store-160538683
```
```sh
$ npm install
```
```sh
$ npm start
```
> Navigate to the homepage 

> Open Redux devtools and check the state update action at work

![image](https://user-images.githubusercontent.com/12577659/45688986-74c0a380-bb5b-11e8-880b-3c933b3d273d.png)

> Signin to see the state updated for the currently logged in user

![image](https://user-images.githubusercontent.com/12577659/45689043-991c8000-bb5b-11e8-93ad-1a4d7234212d.png)

![image](https://user-images.githubusercontent.com/12577659/45689138-d84ad100-bb5b-11e8-9dd7-5135f77985b1.png)

#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#160538683](https://www.pivotaltracker.com/story/show/160538683)

2018-09-18 13:01 UTC, dcDalin commented
<!--
  1 failure:  a `console.log` w...
  1 warning:  :exclamation: Big PR
  
  
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  a `console.log` was left in file (src/index.js)
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :exclamation: Big PR
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-09-18 13:22 UTC, janetnim approved these changes

2018-09-18 13:34 UTC, migot01 approved these changes

2018-09-18 16:55 UTC, jmnyarega commented on src/Home/containers/index.js
> +
Lose this empty line

2018-09-18 17:00 UTC, jmnyarega commented on src/reducers/index.js
> +	exampleReducer,
We can get rid of exampleReducer, if we don't need it

2018-09-18 17:20 UTC, jmnyarega requested changes

2018-09-18 17:20 UTC, jmnyarega commented on src/StateUpdate/updateState.js
> +export default updateState;
I will prefer a different approach: 

* Let's breakdown this code:

1. Move the decoding part of your code a helper function, I presume should be like this 
      
```jsx 
         import jwt_decode from 'jwt-decode';
         const activeUser = () {
           const token = localStorage.getItem('token');
           const  user = token ? jwt_decode(token) : {}
           return user;
        }
```
This will only be responsible in decoding user data.  ☝️ 

2. Create a thunk which will be basically be running the decode function and returning the payload
```jsx
         const export getActiveUser = () => {
            return((dispatch) => {
               const activeUser = decodeUser();
               // loadActiveUser is an actionCreator that you should create
               return dispatch(loadActiveUser(activeUser));
          });
       };
```
Then you can use the above action in your reducer. I like this pattern because it conforms to the current pattern we are using. But most importantly you are only going to run the decode function when you need it, not each time you your load the application as you have approached it. Kindly make the changes I have suggested

2018-09-18 17:20 UTC, jmnyarega commented on src/actions/types.js
> +export const UPDATE_STATE = 'UPDATE_STATE';
Let's change this variable and value to `ACTIVE_USER`

2018-09-18 17:20 UTC, jmnyarega commented on src/index.js
> +  <Provider store={store} loggedInUser={updateState()}>
Please let's user the approach suggested earlier

2018-09-18 17:20 UTC, jmnyarega commented on src/reducers/updateState.js
> +
This empty object is a no-op should be discarded

2018-09-18 17:20 UTC, jmnyarega commented on src/reducers/updateState.js
> +export default updateStateReducer;
The reducer function & filename does not illustrate what is currently being achieved here

2018-09-18 17:22 UTC, jmnyarega commented on src/reducers/updateState.js
> +
Just have the state initialised to `{}` when passing is a parametre

2018-09-18 19:19 UTC, jmnyarega commented on src/Home/containers/index.js
> +    console.log(getActiveUser());
Remove the debug statement

2018-09-19 07:50 UTC, jmnyarega requested changes

2018-09-19 07:50 UTC, jmnyarega commented on src/index.js
> -}
Why was this removed?

2018-09-19 07:53 UTC, johnmusiu commented on src/index.js
> -}
I was deleting `console.log` statements

2018-09-19 07:53 UTC, jmnyarega commented
Can we have these conflicts resolved ?

2018-09-19 07:54 UTC, jmnyarega commented on src/index.js
> -}
I see. Let's get this reverted.

2018-09-19 07:58 UTC, johnmusiu commented on src/index.js
> -}
cool

2018-09-19 09:23 UTC, merged