#160011184 Implement Like Dislike Articles
andela/ah-titans-frontend pull request #34
Opened 2018-09-20 09:00 UTC by janetnim

#### What does this PR do?
Lets an authenticated user like or dislike an artice

#### Description of tasks to be completed
1. Allow authenticated users to like or dislike an article
2. Alert unauthenticated users to login/signup to like or dislike an article

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans-frontend.git
```
```sh
$ git checkout ft-like-dislike-articles-160011184
```
```sh
$ cd ah-titans-frontend
```

> Install the dependencies with the command below.

```sh
$ npm install
```
>Then run the app with the command below.
```sh
$ npm start
```
>Click on an article in the home page and like/dislike

### Relevant screenshots

>An article with no likes/dislikes
<img width="1002" alt="screen shot 2018-09-20 at 11 58 43" src="https://user-images.githubusercontent.com/29487740/45807691-bb81db00-bccc-11e8-932e-730b128a06d2.png">

> Authenticated user likes/dislikes an article
![Uploading Screen Shot 2018-09-20 at 11.59.13.png…]()

> Unauthenticated user tries to like/dislike an article

#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#160011184](https://www.pivotaltracker.com/story/show/160011184)

2018-09-20 09:01 UTC, dcDalin commented
<!--
  0 failure: 
  1 warning:  :exclamation: Big PR
  
  
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :exclamation: Big PR
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-09-20 09:15 UTC, ronaldndirangu approved these changes

2018-09-20 09:16 UTC, migot01 approved these changes

2018-09-20 11:47 UTC, jmnyarega requested changes

2018-09-20 11:47 UTC, jmnyarega commented on src/Home/components/index.js
> +        </Link>
Let's have this indented properly

2018-09-20 11:47 UTC, jmnyarega commented on src/Icons/components/icon.scss
> +}
Add one more extra line at the end of this file

2018-09-20 11:47 UTC, jmnyarega commented on src/Icons/components/index.js
> +		</button>
Let's have this indented properly

2018-09-20 11:47 UTC, jmnyarega commented on src/actions/likeDislike.js
> +};
Lets make use of the axios helper function her

2018-09-21 05:24 UTC, jmnyarega commented
Please solve the conflicts and update your branch

2018-09-21 06:24 UTC, petermwash commented
@jmnyarega Merge conflict solved and the branch is updated now.

2018-09-21 06:36 UTC, merged