#160510057 Update navbar
andela/ah-titans-frontend pull request #35
Opened 2018-09-20 14:21 UTC by johnmusiu

#### What does this PR do?
Implements update navbar and 404 error page

#### Description of tasks to be completed
Updates the look and feel of the navbar by utilizing a SideNav component.
Updates the 404 Page not found UI.

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans-frontend.git
```
```sh
$ cd ah-titans-frontend
```
```sh
$ git checkout -b ch-update-navbar-160510057
```
```sh
$ npm install
```
```sh
$ npm start
```
> Navigate to the homepage 
![image](https://user-images.githubusercontent.com/12577659/45824706-4b3d7e80-bcf9-11e8-9928-c8cdc394b75a.png)

> Click on the navbar burger 
![image](https://user-images.githubusercontent.com/12577659/45824739-614b3f00-bcf9-11e8-9883-b62fd314598b.png)

> Signin to see the state updated sidebar menu
![image](https://user-images.githubusercontent.com/12577659/45824837-893aa280-bcf9-11e8-9a24-4f25c1da3131.png)

#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#160510057](https://www.pivotaltracker.com/story/show/160510057)

2018-09-20 15:55 UTC, dcDalin commented
<!--
  0 failure: 
  1 warning:  :exclamation: Big PR
  
  
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :exclamation: Big PR
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-09-21 05:32 UTC, jmnyarega requested changes

2018-09-21 05:32 UTC, jmnyarega commented on src/Main/main.test.js
> +    // expect(wrapper.find('.not-found')).toHaveLength(1);
Remove these commented lines of code

2018-09-21 05:32 UTC, jmnyarega commented on src/Header/containers/index.js
> +		const { user } = this.props;
Let's have componentWillReceiveProps handling this ..

2018-09-21 05:33 UTC, jmnyarega commented
Update you branch and resolve the conflicts

2018-09-21 05:33 UTC, jmnyarega commented
H

2018-09-21 08:03 UTC, merged