#160011183 Add pagination for articles
andela/ah-titans-frontend pull request #36
Opened 2018-09-20 21:21 UTC by dcDalin

#### What does this PR do?
Adds pagination support for articles

#### Description of tasks to be completed
Users can easily navigate through the numerous articles using the pagination links on the bottom of the page.

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans-frontend.git
```
```sh
$ cd ah-titans-frontend
```
```sh
$ git checkout -b ft-pagination-support-160011183
```
```sh
$ npm install
```

#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#160011183](https://www.pivotaltracker.com/story/show/160011183)

#### Screenshots
<img width="1577" alt="bottompagination" src="https://user-images.githubusercontent.com/30606041/45847611-37fbd480-bd34-11e8-9eab-4fa302c7eaaf.png">

2018-09-20 21:50 UTC, dcDalin commented
<!--
  1 failure:  a `console.log` w...
  0 warning: 
  
  
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  a `console.log` was left in file (src/Home/containers/index.js)
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-09-21 05:31 UTC, ronaldndirangu approved these changes

2018-09-21 05:38 UTC, jmnyarega commented on src/Home/containers/index.js
> +			articles.results.map(article_ => article.push(<ArticlesForm article={article_} key={article.slug} />));
Rename `article_` to `article`

2018-09-21 05:38 UTC, jmnyarega commented on src/Home/containers/index.js
> +						</SnackBar>
Just wondering why you have these changes in this PR

2018-09-21 05:38 UTC, jmnyarega commented on src/actions/viewArticles.js
> +const getArticles = page => (dispatch) => {
Let's practice in documenting our functions, its very important

2018-09-21 05:40 UTC, jmnyarega commented
Update you branch and solve the conflicts

2018-09-21 09:27 UTC, dcDalin commented on src/Home/containers/index.js
> +			articles.results.map(article_ => article.push(<ArticlesForm article={article_} key={article.slug} />));
@jmnyarega There is another `article` variable. The suggested rename will cause the app not to work.

2018-09-21 09:28 UTC, dcDalin commented on src/Home/containers/index.js
> +						</SnackBar>
These were indentation changes automatically made by ESLint and Prettier.

2018-09-21 09:41 UTC, janetnim approved these changes
I have tested your branch and the pagination is fine.

2018-09-21 09:42 UTC, jmnyarega requested changes

2018-09-21 09:42 UTC, jmnyarega commented on src/Home/containers/index.js
> +			articles.results.map(article_ => article.push(<ArticlesForm article={article_} key={article.slug} />));
I know the code will work with having `article_ `, I requested the changes because if doesn't conform to the naming convention we are using.

2018-09-21 09:50 UTC, dcDalin commented on src/Home/containers/index.js
> +			articles.results.map(article_ => article.push(<ArticlesForm article={article_} key={article.slug} />));
@jmnyarega I was not the one who declared the variable. Should I change it to a name like `result` as renaming it to `article` throws an `Uncaught TypeError: article.push is not a function` error.

2018-09-21 09:57 UTC, jmnyarega commented on src/Home/containers/index.js
> +			articles.results.map(article_ => article.push(<ArticlesForm article={article_} key={article.slug} />));
This basically violates most agreed convention about naming variables, I will merge the PR **however** having variable names mixed with symbols is **bad** practice since it does not enhance readability of code. Just writing code that works is not enough especially when working on a team, code readability matters a lot.

2018-09-21 10:00 UTC, dcDalin commented on src/Home/containers/index.js
> +			articles.results.map(article_ => article.push(<ArticlesForm article={article_} key={article.slug} />));
@jmnyarega I completely agree with you. I will raise the issue to the Team so that whoever declared the variable is aware of the conventions and practices.

2018-09-21 10:01 UTC, jmnyarega approved these changes

2018-09-21 10:01 UTC, merged