#160011173 setup sass pre-processing
andela/ah-titans-frontend pull request #5
Opened 2018-08-28 10:22 UTC by migot01

#### What does this PR do?
Setup sass pre-processing

#### Description of tasks to be completed
-Install sass loader and dependancies
-Add sass loader to webpack
#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans-frontend.git
```
```sh
$ git checkout -b ch-setup-sass-160011173
```
```sh
$ npm install
$ npm start
```
#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#160011173](https://www.pivotaltracker.com/story/show/160011173)

2018-08-28 13:50 UTC, ronaldndirangu commented
The node_modules folder should not be pushed to the remote repo. Please add it to the .gitignore file.

2018-08-28 13:51 UTC, petermwash requested changes
Kindly add node_modules in the .gitignore file

2018-08-28 13:52 UTC, janetnim commented
In ```How should this be manually tested?``` on your PR, if follow the steps outlined, the app does not run...probably because I need to install dependencies?...maybe add that to your description

2018-08-28 14:02 UTC, jmnyarega commented on src/App/index.js
> +// import './index.scss';
Remove commented lines

2018-08-28 14:09 UTC, migot01 commented on src/App/index.js
> +// import './index.scss';
cool, it done

2018-08-28 14:10 UTC, janetnim approved these changes

2018-08-28 14:11 UTC, petermwash approved these changes

2018-08-28 19:12 UTC, dcDalin approved these changes

2018-08-29 07:50 UTC, jmnyarega commented
Update your branch

2018-08-29 11:48 UTC, merged